language: node_js
node_js:
  - lts/*

cache:
  directories:
    - node_modules

install:
  - npm install hexo-cli -g
  - npm install

script:
  - hexo g

after_script:
  - cd ./public
  - git init
  - git config user.name "oldmatch"
  - git config user.email "oldmatch24@gmail.com"
  - git add .
  - git commit -m "Update blog content by Travis CI"
  - git push --force --quiet "https://${GH_TOKEN}@github.com/oldmatch/oldmatch.github.io.git" master:master
  - git push --force --quiet "https://${CD_USER}:${CD_TOKEN}@git@e.coding.net:kangzhong/oldmatch/oldmatch.git" master:master

branches:
  only:
    - hexo